
CMM train_err=0.0, err=0.0
Traceback (most recent call last):
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 669, in <module>
    aspect_ratio_l1(d=100, n=100, change_d=True, n_runs=2, s=1, SNR=10, mixture=True, l2=True)
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 442, in aspect_ratio_l1
    err_mm, errs_avm_poly, err_train_mm, errs_train_avm_poly, err_mm_l1, errs_avm_poly_l1, err_train_mm_l1, errs_train_avm_poly_l1,  wmm_l2, w_l2, wmm_l1, w_l1 = margin_classifiers_perf(d=d,n=n,approx_tau=1, SNR=SNR, n_test=1e4, s=s, l1=True, l2=l2, random_flip_prob=sigma, mixture=mixture)
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 286, in margin_classifiers_perf
    result = prob.solve()
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\cvxpy\problems\problem.py", line 481, in solve
    return solve_func(self, *args, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\cvxpy\problems\problem.py", line 1016, in _solve
    self.unpack_results(solution, solving_chain, inverse_data)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\cvxpy\problems\problem.py", line 1341, in unpack_results
    raise error.SolverError(
cvxpy.error.SolverError: Solver 'ECOS' failed. Try another solver, or solve with verbose=True for more information.
Traceback (most recent call last):
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 669, in <module>
    aspect_ratio_l1(d=100, n=100, change_d=True, n_runs=2, s=1, SNR=10, mixture=True, l2=True)
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 442, in aspect_ratio_l1
    err_mm, errs_avm_poly, err_train_mm, errs_train_avm_poly, err_mm_l1, errs_avm_poly_l1, err_train_mm_l1, errs_train_avm_poly_l1,  wmm_l2, w_l2, wmm_l1, w_l1 = margin_classifiers_perf(d=d,n=n,approx_tau=1, SNR=SNR, n_test=1e4, s=s, l1=True, l2=l2, random_flip_prob=sigma, mixture=mixture)
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 286, in margin_classifiers_perf
    result = prob.solve()
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\cvxpy\problems\problem.py", line 481, in solve
    return solve_func(self, *args, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\cvxpy\problems\problem.py", line 1016, in _solve
    self.unpack_results(solution, solving_chain, inverse_data)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\cvxpy\problems\problem.py", line 1341, in unpack_results
    raise error.SolverError(
cvxpy.error.SolverError: Solver 'ECOS' failed. Try another solver, or solve with verbose=True for more information.
Traceback (most recent call last):
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 669, in <module>
    aspect_ratio_l1(d=100, n=100, change_d=True, n_runs=2, s=1, SNR=10, mixture=True, l2=True)
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 442, in aspect_ratio_l1
    err_mm, errs_avm_poly, err_train_mm, errs_train_avm_poly, err_mm_l1, errs_avm_poly_l1, err_train_mm_l1, errs_train_avm_poly_l1,  wmm_l2, w_l2, wmm_l1, w_l1 = margin_classifiers_perf(d=d,n=n,approx_tau=1, SNR=SNR, n_test=1e4, s=s, l1=True, l2=l2, random_flip_prob=sigma, mixture=mixture)
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 286, in margin_classifiers_perf
    result = prob.solve()
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\cvxpy\problems\problem.py", line 481, in solve
    return solve_func(self, *args, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\cvxpy\problems\problem.py", line 1016, in _solve
    self.unpack_results(solution, solving_chain, inverse_data)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\cvxpy\problems\problem.py", line 1341, in unpack_results
    raise error.SolverError(
cvxpy.error.SolverError: Solver 'ECOS' failed. Try another solver, or solve with verbose=True for more information.
Traceback (most recent call last):
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 669, in <module>
    aspect_ratio_l1(d=100, n=100, change_d=True, n_runs=2, s=1, SNR=10, mixture=True, l2=True)
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 442, in aspect_ratio_l1
    err_mm, errs_avm_poly, err_train_mm, errs_train_avm_poly, err_mm_l1, errs_avm_poly_l1, err_train_mm_l1, errs_train_avm_poly_l1,  wmm_l2, w_l2, wmm_l1, w_l1 = margin_classifiers_perf(d=d,n=n,approx_tau=1, SNR=SNR, n_test=1e4, s=s, l1=True, l2=l2, random_flip_prob=sigma, mixture=mixture)
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 286, in margin_classifiers_perf
    result = prob.solve()
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\cvxpy\problems\problem.py", line 481, in solve
    return solve_func(self, *args, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\cvxpy\problems\problem.py", line 1016, in _solve
    self.unpack_results(solution, solving_chain, inverse_data)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\cvxpy\problems\problem.py", line 1341, in unpack_results
    raise error.SolverError(
cvxpy.error.SolverError: Solver 'ECOS' failed. Try another solver, or solve with verbose=True for more information.
Traceback (most recent call last):
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 669, in <module>
    aspect_ratio_l1(d=100, n=100, change_d=True, n_runs=2, s=1, SNR=10, mixture=True, l2=True)
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 442, in aspect_ratio_l1
    err_mm, errs_avm_poly, err_train_mm, errs_train_avm_poly, err_mm_l1, errs_avm_poly_l1, err_train_mm_l1, errs_train_avm_poly_l1,  wmm_l2, w_l2, wmm_l1, w_l1 = margin_classifiers_perf(d=d,n=n,approx_tau=1, SNR=SNR, n_test=1e4, s=s, l1=True, l2=l2, random_flip_prob=sigma, mixture=mixture)
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 286, in margin_classifiers_perf
    result = prob.solve()
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\cvxpy\problems\problem.py", line 481, in solve
    return solve_func(self, *args, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\cvxpy\problems\problem.py", line 1016, in _solve
    self.unpack_results(solution, solving_chain, inverse_data)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\cvxpy\problems\problem.py", line 1341, in unpack_results
    raise error.SolverError(
cvxpy.error.SolverError: Solver 'ECOS' failed. Try another solver, or solve with verbose=True for more information.