2022-04-29 18:52:36,698 INFO    MainThread:28556 [internal.py:wandb_internal():92] W&B internal server running at pid: 28556, started at: 2022-04-29 18:52:36.682793
2022-04-29 18:52:36,701 INFO    WriterThread:28556 [datastore.py:open_for_write():77] open: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220429_185234-2dsrfrhk\run-2dsrfrhk.wandb
2022-04-29 18:52:36,704 DEBUG   SenderThread:28556 [sender.py:send():235] send: header
2022-04-29 18:52:36,704 DEBUG   SenderThread:28556 [sender.py:send():235] send: run
2022-04-29 18:52:37,516 INFO    SenderThread:28556 [dir_watcher.py:__init__():169] watching files in: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220429_185234-2dsrfrhk\files
2022-04-29 18:52:37,518 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: check_version
2022-04-29 18:52:37,533 INFO    SenderThread:28556 [sender.py:_start_run_threads():812] run started: 2dsrfrhk with start time 1651251154
2022-04-29 18:52:37,535 DEBUG   SenderThread:28556 [sender.py:send():235] send: summary
2022-04-29 18:52:37,538 INFO    SenderThread:28556 [sender.py:_save_file():947] saving file wandb-summary.json with policy end
2022-04-29 18:52:37,540 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: check_version
2022-04-29 18:52:38,077 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: run_start
2022-04-29 18:52:38,530 INFO    Thread-11 :28556 [dir_watcher.py:_on_file_created():217] file/dir created: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220429_185234-2dsrfrhk\files\wandb-summary.json
2022-04-29 18:52:39,196 DEBUG   HandlerThread:28556 [meta.py:__init__():37] meta init
2022-04-29 18:52:39,196 DEBUG   HandlerThread:28556 [meta.py:__init__():51] meta init done
2022-04-29 18:52:39,196 DEBUG   HandlerThread:28556 [meta.py:probe():211] probe
2022-04-29 18:52:39,248 DEBUG   HandlerThread:28556 [meta.py:_setup_git():201] setup git
2022-04-29 18:52:39,334 DEBUG   HandlerThread:28556 [meta.py:_setup_git():208] setup git done
2022-04-29 18:52:39,335 DEBUG   HandlerThread:28556 [meta.py:_save_pip():55] save pip
2022-04-29 18:52:39,336 DEBUG   HandlerThread:28556 [meta.py:_save_pip():69] save pip done
2022-04-29 18:52:39,336 DEBUG   HandlerThread:28556 [meta.py:_save_conda():76] save conda
2022-04-29 18:52:39,342 ERROR   HandlerThread:28556 [meta.py:_save_conda():85] Error saving conda packages
Traceback (most recent call last):
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\wandb\sdk\internal\meta.py", line 81, in _save_conda
    subprocess.call(
  File "C:\Users\gizem\anaconda3\envs\iw\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\gizem\anaconda3\envs\iw\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\gizem\anaconda3\envs\iw\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
2022-04-29 18:52:39,344 DEBUG   HandlerThread:28556 [meta.py:_save_conda():86] save conda done
2022-04-29 18:52:39,344 DEBUG   HandlerThread:28556 [meta.py:probe():249] probe done
2022-04-29 18:52:39,519 DEBUG   SenderThread:28556 [sender.py:send():235] send: files
2022-04-29 18:52:39,519 INFO    SenderThread:28556 [sender.py:_save_file():947] saving file wandb-metadata.json with policy now
2022-04-29 18:52:39,520 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: stop_status
2022-04-29 18:52:39,522 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: stop_status
2022-04-29 18:52:39,527 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: partial_history
2022-04-29 18:52:39,535 INFO    Thread-11 :28556 [dir_watcher.py:_on_file_created():217] file/dir created: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220429_185234-2dsrfrhk\files\output.log
2022-04-29 18:52:39,536 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: partial_history
2022-04-29 18:52:39,538 INFO    Thread-11 :28556 [dir_watcher.py:_on_file_created():217] file/dir created: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220429_185234-2dsrfrhk\files\requirements.txt
2022-04-29 18:52:39,539 INFO    Thread-11 :28556 [dir_watcher.py:_on_file_created():217] file/dir created: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220429_185234-2dsrfrhk\files\wandb-metadata.json
2022-04-29 18:52:39,540 INFO    Thread-11 :28556 [dir_watcher.py:_on_file_created():217] file/dir created: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220429_185234-2dsrfrhk\files\conda-environment.yaml
2022-04-29 18:52:40,515 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:52:40,544 INFO    Thread-11 :28556 [dir_watcher.py:_on_file_modified():230] file/dir modified: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220429_185234-2dsrfrhk\files\output.log
2022-04-29 18:52:45,627 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:52:50,750 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:52:55,869 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:52:56,995 ERROR   Thread-17 :28556 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000020B7FBCB2B0>: Failed to establish a new connection: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020B7FBCB2B0>: Failed to establish a new connection: [WinError 10053] An established connection was aborted by the software in your host machine'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\wandb\sdk\internal\internal_api.py", line 141, in execute
    return self.client.execute(*args, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020B7FBCB2B0>: Failed to establish a new connection: [WinError 10053] An established connection was aborted by the software in your host machine'))
2022-04-29 18:52:56,996 WARNING FileStreamThread:28556 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)). func: <bound method Session.post of <requests.sessions.Session object at 0x0000020B7F90EF20>>, args: ('https://api.wandb.ai/files/sml-eth/noisy-fair/2dsrfrhk/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{}']}}, 'dropped': 0}}
2022-04-29 18:52:56,997 ERROR   SenderThread:28556 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000020B7FBCB400>: Failed to establish a new connection: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020B7FBCB400>: Failed to establish a new connection: [WinError 10053] An established connection was aborted by the software in your host machine'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\wandb\sdk\internal\internal_api.py", line 141, in execute
    return self.client.execute(*args, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020B7FBCB400>: Failed to establish a new connection: [WinError 10053] An established connection was aborted by the software in your host machine'))
2022-04-29 18:53:00,955 DEBUG   SenderThread:28556 [sender.py:send():235] send: telemetry
2022-04-29 18:53:00,955 DEBUG   SenderThread:28556 [sender.py:send():235] send: history
2022-04-29 18:53:00,956 DEBUG   SenderThread:28556 [sender.py:send():235] send: summary
2022-04-29 18:53:00,961 INFO    SenderThread:28556 [sender.py:_save_file():947] saving file wandb-summary.json with policy end
2022-04-29 18:53:00,964 DEBUG   SenderThread:28556 [sender.py:send():235] send: history
2022-04-29 18:53:00,964 DEBUG   SenderThread:28556 [sender.py:send():235] send: summary
2022-04-29 18:53:00,966 INFO    SenderThread:28556 [sender.py:_save_file():947] saving file wandb-summary.json with policy end
2022-04-29 18:53:00,967 DEBUG   SenderThread:28556 [sender.py:send():235] send: telemetry
2022-04-29 18:53:00,967 DEBUG   SenderThread:28556 [sender.py:send():235] send: telemetry
2022-04-29 18:53:00,967 DEBUG   SenderThread:28556 [sender.py:send():235] send: exit
2022-04-29 18:53:00,968 INFO    SenderThread:28556 [sender.py:send_exit():371] handling exit code: 0
2022-04-29 18:53:00,968 INFO    SenderThread:28556 [sender.py:send_exit():373] handling runtime: 2
2022-04-29 18:53:00,969 INFO    SenderThread:28556 [sender.py:_save_file():947] saving file wandb-summary.json with policy end
2022-04-29 18:53:00,969 INFO    SenderThread:28556 [sender.py:send_exit():379] send defer
2022-04-29 18:53:00,970 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:00,970 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:00,971 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:00,972 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:00,972 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: defer
2022-04-29 18:53:00,973 INFO    HandlerThread:28556 [handler.py:handle_request_defer():164] handle defer: 0
2022-04-29 18:53:00,973 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: defer
2022-04-29 18:53:00,973 INFO    SenderThread:28556 [sender.py:send_request_defer():388] handle sender defer: 0
2022-04-29 18:53:00,974 INFO    SenderThread:28556 [sender.py:transition_state():392] send defer: 1
2022-04-29 18:53:00,974 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: defer
2022-04-29 18:53:00,975 INFO    HandlerThread:28556 [handler.py:handle_request_defer():164] handle defer: 1
2022-04-29 18:53:01,462 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: defer
2022-04-29 18:53:01,462 INFO    SenderThread:28556 [sender.py:send_request_defer():388] handle sender defer: 1
2022-04-29 18:53:01,462 INFO    SenderThread:28556 [sender.py:transition_state():392] send defer: 2
2022-04-29 18:53:01,462 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:01,463 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:01,463 DEBUG   SenderThread:28556 [sender.py:send():235] send: stats
2022-04-29 18:53:01,464 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: defer
2022-04-29 18:53:01,464 INFO    HandlerThread:28556 [handler.py:handle_request_defer():164] handle defer: 2
2022-04-29 18:53:01,464 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: defer
2022-04-29 18:53:01,464 INFO    SenderThread:28556 [sender.py:send_request_defer():388] handle sender defer: 2
2022-04-29 18:53:01,465 INFO    SenderThread:28556 [sender.py:transition_state():392] send defer: 3
2022-04-29 18:53:01,465 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: defer
2022-04-29 18:53:01,465 INFO    HandlerThread:28556 [handler.py:handle_request_defer():164] handle defer: 3
2022-04-29 18:53:01,465 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: defer
2022-04-29 18:53:01,465 INFO    SenderThread:28556 [sender.py:send_request_defer():388] handle sender defer: 3
2022-04-29 18:53:01,466 INFO    SenderThread:28556 [sender.py:transition_state():392] send defer: 4
2022-04-29 18:53:01,466 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: defer
2022-04-29 18:53:01,466 INFO    HandlerThread:28556 [handler.py:handle_request_defer():164] handle defer: 4
2022-04-29 18:53:01,466 DEBUG   SenderThread:28556 [sender.py:send():235] send: summary
2022-04-29 18:53:01,467 INFO    SenderThread:28556 [sender.py:_save_file():947] saving file wandb-summary.json with policy end
2022-04-29 18:53:01,467 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: defer
2022-04-29 18:53:01,467 INFO    SenderThread:28556 [sender.py:send_request_defer():388] handle sender defer: 4
2022-04-29 18:53:01,468 INFO    SenderThread:28556 [sender.py:transition_state():392] send defer: 5
2022-04-29 18:53:01,468 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: defer
2022-04-29 18:53:01,468 INFO    HandlerThread:28556 [handler.py:handle_request_defer():164] handle defer: 5
2022-04-29 18:53:01,468 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: defer
2022-04-29 18:53:01,469 INFO    SenderThread:28556 [sender.py:send_request_defer():388] handle sender defer: 5
2022-04-29 18:53:01,571 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:01,749 INFO    Thread-11 :28556 [dir_watcher.py:_on_file_modified():230] file/dir modified: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220429_185234-2dsrfrhk\files\wandb-summary.json
2022-04-29 18:53:02,201 INFO    Thread-17 :28556 [upload_job.py:push():137] Uploaded file C:\Users\gizem\AppData\Local\Temp\tmpte2rmiijwandb\17dz1dc1-wandb-metadata.json
2022-04-29 18:53:02,375 INFO    SenderThread:28556 [sender.py:transition_state():392] send defer: 6
2022-04-29 18:53:02,376 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:02,380 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: defer
2022-04-29 18:53:02,381 INFO    HandlerThread:28556 [handler.py:handle_request_defer():164] handle defer: 6
2022-04-29 18:53:02,384 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: defer
2022-04-29 18:53:02,386 INFO    SenderThread:28556 [sender.py:send_request_defer():388] handle sender defer: 6
2022-04-29 18:53:02,386 INFO    SenderThread:28556 [dir_watcher.py:finish():283] shutting down directory watcher
2022-04-29 18:53:02,491 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:02,761 INFO    SenderThread:28556 [dir_watcher.py:_on_file_modified():230] file/dir modified: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220429_185234-2dsrfrhk\files\config.yaml
2022-04-29 18:53:02,764 INFO    SenderThread:28556 [dir_watcher.py:finish():313] scan: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220429_185234-2dsrfrhk\files
2022-04-29 18:53:02,766 INFO    SenderThread:28556 [dir_watcher.py:finish():327] scan save: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220429_185234-2dsrfrhk\files\conda-environment.yaml conda-environment.yaml
2022-04-29 18:53:02,769 INFO    SenderThread:28556 [dir_watcher.py:finish():327] scan save: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220429_185234-2dsrfrhk\files\config.yaml config.yaml
2022-04-29 18:53:02,771 INFO    SenderThread:28556 [dir_watcher.py:finish():327] scan save: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220429_185234-2dsrfrhk\files\output.log output.log
2022-04-29 18:53:02,775 INFO    SenderThread:28556 [dir_watcher.py:finish():327] scan save: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220429_185234-2dsrfrhk\files\requirements.txt requirements.txt
2022-04-29 18:53:02,779 INFO    SenderThread:28556 [dir_watcher.py:finish():327] scan save: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220429_185234-2dsrfrhk\files\wandb-metadata.json wandb-metadata.json
2022-04-29 18:53:02,780 INFO    SenderThread:28556 [dir_watcher.py:finish():327] scan save: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220429_185234-2dsrfrhk\files\wandb-summary.json wandb-summary.json
2022-04-29 18:53:02,826 INFO    SenderThread:28556 [sender.py:transition_state():392] send defer: 7
2022-04-29 18:53:02,831 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:02,840 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: defer
2022-04-29 18:53:02,841 INFO    HandlerThread:28556 [handler.py:handle_request_defer():164] handle defer: 7
2022-04-29 18:53:02,843 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: defer
2022-04-29 18:53:02,844 INFO    SenderThread:28556 [sender.py:send_request_defer():388] handle sender defer: 7
2022-04-29 18:53:02,844 INFO    SenderThread:28556 [file_pusher.py:finish():145] shutting down file pusher
2022-04-29 18:53:02,953 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:02,954 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:03,078 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:03,079 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:03,186 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:03,187 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:03,294 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:03,294 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:03,402 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:03,402 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:03,518 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:03,519 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:03,633 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:03,634 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:03,749 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:03,750 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:03,858 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:03,859 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:03,966 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:03,967 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:04,084 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:04,085 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:04,221 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:04,246 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:04,378 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:04,380 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:04,495 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:04,496 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:04,609 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:04,610 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:04,724 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:04,725 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:04,831 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:04,832 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:04,941 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:04,941 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:05,055 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:05,056 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:05,163 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:05,164 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:05,279 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:05,280 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:05,395 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:05,396 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:05,511 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:05,511 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:05,628 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:05,629 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:05,753 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:05,754 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:05,865 INFO    Thread-20 :28556 [upload_job.py:push():137] Uploaded file C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220429_185234-2dsrfrhk\files\requirements.txt
2022-04-29 18:53:05,887 INFO    Thread-19 :28556 [upload_job.py:push():137] Uploaded file C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220429_185234-2dsrfrhk\files\output.log
2022-04-29 18:53:05,889 INFO    Thread-18 :28556 [upload_job.py:push():137] Uploaded file C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220429_185234-2dsrfrhk\files\config.yaml
2022-04-29 18:53:05,891 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:05,893 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:05,994 INFO    Thread-21 :28556 [upload_job.py:push():137] Uploaded file C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220429_185234-2dsrfrhk\files\wandb-summary.json
2022-04-29 18:53:06,008 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:06,009 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:06,124 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:06,126 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:06,200 INFO    Thread-10 (_thread_body):28556 [sender.py:transition_state():392] send defer: 8
2022-04-29 18:53:06,204 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: defer
2022-04-29 18:53:06,204 INFO    HandlerThread:28556 [handler.py:handle_request_defer():164] handle defer: 8
2022-04-29 18:53:06,206 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: defer
2022-04-29 18:53:06,207 INFO    SenderThread:28556 [sender.py:send_request_defer():388] handle sender defer: 8
2022-04-29 18:53:06,239 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:06,405 INFO    SenderThread:28556 [sender.py:transition_state():392] send defer: 9
2022-04-29 18:53:06,406 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:06,407 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: defer
2022-04-29 18:53:06,407 INFO    HandlerThread:28556 [handler.py:handle_request_defer():164] handle defer: 9
2022-04-29 18:53:06,407 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: defer
2022-04-29 18:53:06,407 INFO    SenderThread:28556 [sender.py:send_request_defer():388] handle sender defer: 9
2022-04-29 18:53:06,408 INFO    SenderThread:28556 [sender.py:transition_state():392] send defer: 10
2022-04-29 18:53:06,409 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: defer
2022-04-29 18:53:06,409 INFO    HandlerThread:28556 [handler.py:handle_request_defer():164] handle defer: 10
2022-04-29 18:53:06,409 DEBUG   SenderThread:28556 [sender.py:send():235] send: final
2022-04-29 18:53:06,409 DEBUG   SenderThread:28556 [sender.py:send():235] send: footer
2022-04-29 18:53:06,409 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: defer
2022-04-29 18:53:06,409 INFO    SenderThread:28556 [sender.py:send_request_defer():388] handle sender defer: 10
2022-04-29 18:53:06,523 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: poll_exit
2022-04-29 18:53:06,523 DEBUG   SenderThread:28556 [sender.py:send_request():249] send_request: poll_exit
2022-04-29 18:53:06,523 INFO    SenderThread:28556 [file_pusher.py:join():150] waiting for file pusher
2022-04-29 18:53:10,609 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: sampled_history
2022-04-29 18:53:10,616 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: get_summary
2022-04-29 18:53:10,623 DEBUG   HandlerThread:28556 [handler.py:handle_request():141] handle_request: shutdown
2022-04-29 18:53:10,624 INFO    HandlerThread:28556 [handler.py:finish():790] shutting down handler
2022-04-29 18:53:11,437 INFO    WriterThread:28556 [datastore.py:close():281] close: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220429_185234-2dsrfrhk\run-2dsrfrhk.wandb
2022-04-29 18:53:11,483 INFO    SenderThread:28556 [sender.py:finish():1107] shutting down sender
2022-04-29 18:53:11,484 INFO    SenderThread:28556 [file_pusher.py:finish():145] shutting down file pusher
2022-04-29 18:53:11,485 INFO    SenderThread:28556 [file_pusher.py:join():150] waiting for file pusher
2022-04-29 18:53:11,491 INFO    MainThread:28556 [internal.py:handle_exit():82] Internal process exited
