
Epoch: 0 Loss: 0.6924 Train_Acc: 0.5469 Val_Accuracy: 0.5000
Epoch: 1 Loss: 0.6924 Train_Acc: 0.5469 Val_Accuracy: 0.5000
Epoch: 2 Loss: 0.6924 Train_Acc: 0.5469 Val_Accuracy: 0.5000
Epoch: 3 Loss: 0.6923 Train_Acc: 0.5469 Val_Accuracy: 0.5000
Epoch: 4 Loss: 0.6923 Train_Acc: 0.5469 Val_Accuracy: 0.5000
Epoch: 5 Loss: 0.6923 Train_Acc: 0.5469 Val_Accuracy: 0.5000
Epoch: 6 Loss: 0.6923 Train_Acc: 0.5469 Val_Accuracy: 0.5000
Epoch: 7 Loss: 0.6922 Train_Acc: 0.5469 Val_Accuracy: 0.5000
Epoch: 8 Loss: 0.6922 Train_Acc: 0.5469 Val_Accuracy: 0.5000
Epoch: 9 Loss: 0.6921 Train_Acc: 0.5469 Val_Accuracy: 0.5000
Traceback (most recent call last):
  File "C:\Users\gizem\Documents\GitHub\noisy_fair\fmnist_binary_convnet.py", line 419, in <module>
    train_with_both_losses(n_train=int(sys.argv[1]), batch_size=int(sys.argv[1]))
  File "C:\Users\gizem\Documents\GitHub\noisy_fair\fmnist_binary_convnet.py", line 343, in train_with_both_losses
    ce_test_final = test_acc
NameError: name 'test_acc' is not defined